import type { VenueData } from "@/types";

export const VENUES: VenueData[] = [
  // ── Major Memphis venues ──────────────────────────────────────────────────
  {
    name: "FedExForum",
    slug: "fedexforum",
    address: "191 Beale St",
    city: "Memphis",
    state: "TN",
    zip: "38103",
    lat: 35.1382,
    lng: -90.0506,
    capacity: 18400,
    website: "https://www.fedexforum.com",
    scrapeUrl: "https://www.fedexforum.com/events",
  },
  {
    name: "Orpheum Theatre",
    slug: "orpheum",
    address: "203 S Main St",
    city: "Memphis",
    state: "TN",
    zip: "38103",
    lat: 35.1435,
    lng: -90.0517,
    capacity: 2800,
    website: "https://www.orpheum-memphis.com",
    scrapeUrl: "https://www.orpheum-memphis.com/events",
  },
  {
    name: "Minglewood Hall",
    slug: "minglewood-hall",
    address: "1555 Madison Ave",
    city: "Memphis",
    state: "TN",
    zip: "38104",
    lat: 35.1477,
    lng: -90.0302,
    capacity: 1500,
    website: "https://www.minglewoodhall.com",
    scrapeUrl: "https://www.minglewoodhall.com/events",
  },
  {
    name: "New Daisy Theatre",
    slug: "new-daisy",
    address: "330 Beale St",
    city: "Memphis",
    state: "TN",
    zip: "38103",
    lat: 35.1389,
    lng: -90.0522,
    capacity: 1100,
    website: "https://www.newdaisy.com",
    scrapeUrl: "https://www.newdaisy.com/events",
  },
  {
    name: "Levitt Shell",
    slug: "levitt-shell",
    address: "1928 Poplar Ave",
    city: "Memphis",
    state: "TN",
    zip: "38104",
    lat: 35.1502,
    lng: -90.0461,
    capacity: 5000,
    website: "https://www.levittshell.org",
    scrapeUrl: "https://www.levittshell.org/events",
  },
  {
    name: "Crosstown Theater",
    slug: "crosstown-theater",
    address: "1350 Concourse Ave",
    city: "Memphis",
    state: "TN",
    zip: "38104",
    lat: 35.1541,
    lng: -90.0365,
    capacity: 1000,
    website: "https://crosstownconcourse.com",
    scrapeUrl: "https://crosstownconcourse.com/events",
  },
  {
    name: "Lafayette's Music Room",
    slug: "lafayettes",
    address: "2119 Madison Ave",
    city: "Memphis",
    state: "TN",
    zip: "38104",
    lat: 35.1468,
    lng: -90.0240,
    capacity: 400,
    website: "https://www.lafayettesmusicroom.com",
    scrapeUrl: "https://www.lafayettesmusicroom.com/calendar",
  },
  {
    name: "Hi-Tone Cafe",
    slug: "hi-tone",
    address: "412 N Cleveland St",
    city: "Memphis",
    state: "TN",
    zip: "38104",
    lat: 35.1508,
    lng: -90.0322,
    capacity: 350,
    website: "https://www.hitonememphis.com",
    scrapeUrl: "https://www.hitonememphis.com/events",
  },
  {
    name: "Graceland Soundstage",
    slug: "graceland-soundstage",
    address: "3765 Elvis Presley Blvd",
    city: "Memphis",
    state: "TN",
    zip: "38116",
    lat: 35.0474,
    lng: -90.0266,
    capacity: 1000,
    website: "https://www.graceland.com",
    scrapeUrl: "https://www.graceland.com/events",
  },
  {
    name: "Young Avenue Deli",
    slug: "young-avenue-deli",
    address: "2119 Young Ave",
    city: "Memphis",
    state: "TN",
    zip: "38104",
    lat: 35.1244,
    lng: -90.0208,
    capacity: 300,
    website: "https://www.youngavenuedeli.com",
    scrapeUrl: "https://www.youngavenuedeli.com/events",
  },
  {
    name: "Railgarten",
    slug: "railgarten",
    address: "2166 Central Ave",
    city: "Memphis",
    state: "TN",
    zip: "38104",
    lat: 35.1261,
    lng: -90.0174,
    capacity: 600,
    website: "https://www.railgarten.com",
    scrapeUrl: "https://www.railgarten.com/events",
  },
  {
    name: "Mud Island Amphitheater",
    slug: "mud-island",
    address: "125 N Front St",
    city: "Memphis",
    state: "TN",
    zip: "38103",
    lat: 35.1558,
    lng: -90.0575,
    capacity: 5000,
    website: "https://www.mudisland.com",
  },
  {
    name: "Earnestine & Hazel's",
    slug: "earnestine-hazels",
    address: "531 S Main St",
    city: "Memphis",
    state: "TN",
    zip: "38103",
    lat: 35.1388,
    lng: -90.0491,
    capacity: 200,
    website: "https://www.earnestinehazelsjukejoint.com",
  },
  // ── Mississippi venues ────────────────────────────────────────────────────
  {
    name: "BankPlus Amphitheater at Snowden Grove",
    slug: "bankplus-amphitheater",
    address: "6005 Snowden Ln",
    city: "Southaven",
    state: "MS",
    zip: "38671",
    lat: 34.9549,
    lng: -89.9834,
    capacity: 8000,
    website: "https://www.bankplusamphitheater.com",
    scrapeUrl: "https://www.bankplusamphitheater.com/events",
  },
  {
    name: "Landers Center",
    slug: "landers-center",
    address: "4560 Venture Dr",
    city: "Southaven",
    state: "MS",
    zip: "38671",
    lat: 34.9408,
    lng: -90.0026,
    capacity: 9000,
    website: "https://www.landerscenter.com",
    scrapeUrl: "https://www.landerscenter.com/events",
  },
  {
    name: "The Lyric Oxford",
    slug: "lyric-oxford",
    address: "1006 Van Buren Ave",
    city: "Oxford",
    state: "MS",
    zip: "38655",
    lat: 34.3668,
    lng: -89.5246,
    capacity: 1000,
    website: "https://www.thelyricoxford.com",
    scrapeUrl: "https://www.thelyricoxford.com/events",
  },
];
